spring.application.name=web_flux_demo

server.port=8080
spring.webflux.base-path=/webflux

r2dbc.host=localhost
r2dbc.port=5432
r2dbc.dbase=webflux
r2dbc.username=postgres
r2dbc.password=Vitalex88

callback.total.timeout.seconds=30
callback.memory.delay.millis=500

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.min-idle=1
spring.r2dbc.pool.max-size=10

spring.r2dbc.url=r2dbc:postgresql://${r2dbc.host}:${r2dbc.port}/${r2dbc.dbase}
spring.r2dbc.username=${r2dbc.username}
spring.r2dbc.password=${r2dbc.password}

spring.sql.init.platform=postgres
spring.sql.init.mode=always

logging.level.root=info
logging.level.ru.vitos.local.webflux=debug

spring.liquibase.change-log=classpath:db/scheme-webflux-changelog.xml

##--------------------- SECURITY KEYCLOAK ----------------------------------------------------------------------------
keycloak.server.url=http://localhost:8443
keycloak.admin.realm=SpringBootKeycloak

# если понадобиться аутентификация на клиенте - необходимо добавить настройки для client

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}/protocol/openid-connect/certs
##--------------------- SECURITY KEYCLOAK ----------------------------------------------------------------------------
