spring.application.name=web_flux_demo

server.port=8080
spring.webflux.base-path=/webflux

r2dbc.host=localhost
r2dbc.port=5432
r2dbc.dbase=webflux
r2dbc.username=postgres
r2dbc.password=Vitalex88

callback.total.timeout.seconds=30
callback.memory.delay.millis=500

spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.min-idle=1
spring.r2dbc.pool.max-size=10

spring.r2dbc.url=r2dbc:postgresql://${r2dbc.host}:${r2dbc.port}/${r2dbc.dbase}
spring.r2dbc.username=${r2dbc.username}
spring.r2dbc.password=${r2dbc.password}

spring.sql.init.platform=postgres
spring.sql.init.mode=always

logging.level.root=info
logging.level.ru.vitos.local.webflux=debug

spring.liquibase.change-log=classpath:db/scheme-webflux-changelog.xml

##--------------------- SECURITY KEYCLOAK ----------------------------------------------------------------------------
keycloak.server.url=http://localhost:8443

keycloak.master.admin.realm=master
keycloak.master.admin.client-id=admin-client
keycloak.master.admin.secret=TapOEMvNpD4ZajAcAzdXQriUNYHjzRNt

keycloak.admin.realm=SpringBootKeycloak
keycloak.admin.client_id=login-admin
keycloak.admin.client_secret=6dMULRFc4gnadbs4xaqzvUueaQNJJSBS

spring.security.oauth2.client.registration.keycloak.client-id=login-web
spring.security.oauth2.client.registration.keycloak.client-secret=WbP46pdXfGG1Gmpw5sS859vL5NgLN2t4
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.server.url}/realms/${keycloak.admin.realm}/protocol/openid-connect/certs
##--------------------- SECURITY KEYCLOAK ----------------------------------------------------------------------------
